Repository openssl/openssl, pull requests merged in 2020-03, with the labels that each got.

#11191 crypto/perlasm/x86_64-xlate.pl: detect GNU as to deal with quirks
  crypto/perlasm/x86_64-xlate.pl
Labels: approval: ready to merge, branch: master

#11186 .travis.yml: where it matters, have build and source nesting levels differ
  .travis.yml
Labels: approval: ready to merge, branch: master

#11217 config, Configure: move the check of removed crypto/ sub-systems
  Configure
  config
Labels: approval: ready to merge, branch: master

#11102 Improve small block cipher performance
  providers/implementations/ciphers/cipher_aes_ocb.c
  providers/implementations/ciphers/ciphercommon.c
  providers/implementations/ciphers/ciphercommon_block.c
Labels: approval: ready to merge, branch: master

#11126 Refactor CRMF_poposigningkey_init() to work with provider keys
  crypto/crmf/crmf_lib.c
Labels: approval: ready to merge, branch: master

#11258 util/wrap.pl: do not look at EXE_SHELL
  util/wrap.pl
Labels: approval: ready to merge, branch: master

#11275 DOCS: Fix documentation on asymmetric keydata types
  doc/man7/provider-keymgmt.pod
Labels: approval: ready to merge, branch: master

#11206 Andoid cross compile: change ANDROID_NDK_HOME to ANDROID_NDK_ROOT
  Configurations/15-android.conf
  NOTES.ANDROID
Labels: approval: ready to merge, branch: 1.1.1, branch: master

#11238 Configurations: Fix "android" configuration target
  Configurations/15-android.conf
Labels: approval: ready to merge, branch: 1.1.1, branch: master

#11315 Fix RSA structure
  crypto/rsa/rsa_local.h
Labels: approval: ready to merge, branch: master

#11279 DOCS: Fix the description of OSSL_PARAM_allocate_from_text()
  doc/man3/OSSL_PARAM_allocate_from_text.pod
Labels: approval: ready to merge, branch: master

#11329 Fix legacy_ctrl_to_param() to pay better attention to keytype
  crypto/evp/pmeth_lib.c
Labels: approval: ready to merge, branch: master

#11345 Release commits for 1.1.1e
  CHANGES
  NEWS
  README
  include/openssl/opensslv.h
Labels: branch: 1.1.1, urgent

#11374 DH, DSA, EC_KEY: Fix exporters to allow domain parameter keys
  crypto/dh/dh_ameth.c
  crypto/dsa/dsa_ameth.c
  crypto/ec/ec_ameth.c
  crypto/ec/ecx_meth.c
  crypto/rsa/rsa_ameth.c
Labels: approval: ready to merge, branch: master

#11379 util/wrap.pl: Correct exit code when signalled
  util/wrap.pl
Labels: approval: ready to merge, branch: master

#11391 EC: Refactor ec_curve_name2nid() to accept NIST curve names
  crypto/ec/ec_curve.c
Labels: approval: ready to merge, branch: master

#11394 PROV: Fix EC_KEY exporters to allow domain parameter keys
  crypto/ec/ec_backend.c
  providers/implementations/keymgmt/ec_kmgmt.c
Labels: approval: ready to merge, branch: master

#11446 111f release commits
  CHANGES
  NEWS
  README
  include/openssl/opensslv.h
Labels: approval: done, branch: 1.1.1, urgent

#11171 Windows makefile generator: Don't delete long lists of files in one go
  Configurations/windows-makefile.tmpl
Labels: approval: ready to merge, branch: master
